version: "3"
services:
  'ardt_reverse_proxy':
    container_name: ardt_reverse_proxy
    environment: 
      - NODE_ENV=development
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./:/usr/app
    expose: 
      - "80"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "ardt_network"
    restart: "always"

networks:
  ardt_network:
    external: true