services:
  'ardt_reverse_proxy':
    container_name: ardt_reverse_proxy
    environment: 
      - NODE_ENV=development
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./:/usr/app
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    expose: 
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "ardt_network"
    restart: "always"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  ardt_network:
    external: true
